FROM registry.access.redhat.com/ubi9 AS ubi-micro-build
FROM quay.io/keycloak/keycloak:25.0.6 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange,admin-fine-grained-authz,declarative-user-profile
ENV KC_DB=postgres
ENV KC_HTTP_ENABLED=true
ENV PROXY_ADDRESS_FORWARDING=true
ENV KC_HOSTNAME=localhost
ENV KC_LOG_LEVEL=INFO

# Copy themes and configuration
COPY /theme/keywind /opt/keycloak/themes/keywind
COPY config/test-realm.json /opt/keycloak/data/import/
COPY config/cli/custom-cli.properties /opt/keycloak/conf/

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:25.0.6
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Create an admin user
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=admin

# Expose port 8080
EXPOSE 8080

# Start Keycloak
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]